[package]
name = "kaat_examples"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kaat = { path = "../kaat_proc_macro/" }
